dataset_name: task6_Empathetic_Captioning
task: humanibench_t6_empathic
include: ../_default_template_yaml
process_results_use_image: true
doc_to_visual: !function utils_t6_empathic.doc_to_visual
doc_to_text: !function utils_t6_empathic.doc_to_text
doc_to_messages: !function utils_t6_empathic.doc_to_messages
doc_to_target: "empathic_prompt"
process_results: !function utils_t6_empathic.process_results
metric_list:
  - metric: empathy
    aggregation: !function utils_t6_empathic.aggregate_empathy
    higher_is_better: true
  - metric: anxiety
    aggregation: !function utils_t6_empathic.aggregate_anxiety
    higher_is_better: false
  - metric: sadness
    aggregation: !function utils_t6_empathic.aggregate_sadness
    higher_is_better: false
  - metric: joy
    aggregation: !function utils_t6_empathic.aggregate_joy
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
