dataset_name: task1_Scene_Understanding
task: humanibench_t1_plain
include: ../_default_template_yaml
process_docs: !function utils_t1_plain.process_docs
doc_to_visual: !function utils_t1_plain.doc_to_visual
doc_to_text: !function utils_t1_plain.doc_to_text
doc_to_messages: !function utils_t1_plain.doc_to_messages
doc_to_target: "Answer"
process_results: !function utils_t1_plain.process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils_t1_plain.aggregate_accuracy
    higher_is_better: true
  - metric: bias
    aggregation: !function utils_t1_plain.aggregate_bias
    higher_is_better: false
  - metric: hallucination
    aggregation: !function utils_t1_plain.aggregate_hallucination
    higher_is_better: false
  - metric: faithfulness
    aggregation: !function utils_t1_plain.aggregate_faithfulness
    higher_is_better: true
  - metric: contextual_relevance
    aggregation: !function utils_t1_plain.aggregate_contextual_relevance
    higher_is_better: true
  - metric: coherence
    aggregation: !function utils_t1_plain.aggregate_coherence
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
